services:
  - type: web
    name: backend-meeting-logs
    env: docker
    plan: free
    envVars:
      - key: APP_NAME
        value: "Meeting Logs API"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: "base64:p+TZ25AHfSOyYr3O+RU6BMJvxXI+eFN8+D9pNAcC1yQ="
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://backend-meeting-logs.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: meeting-logs-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: meeting-logs-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: meeting-logs-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: meeting-logs-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: meeting-logs-db
          property: password

databases:
  - name: meeting-logs-db
    databaseName: meeting_logs
    user: meeting_user
    plan: free
